// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBacklinks(arg1) {
  return window['go']['main']['App']['GetBacklinks'](arg1);
}

export function GetPage(arg1) {
  return window['go']['main']['App']['GetPage'](arg1);
}

export function GetPageList() {
  return window['go']['main']['App']['GetPageList']();
}

export function LoadDirectory(arg1) {
  return window['go']['main']['App']['LoadDirectory'](arg1);
}
