// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBlock(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Record<string, any>>;

export function AddBlockAtPath(arg1:string,arg2:main.BlockPath,arg3:string):Promise<Record<string, any>>;

export function GetBacklinks(arg1:string):Promise<Record<string, Array<string>>>;

export function GetPage(arg1:string):Promise<main.PageData>;

export function GetPageList():Promise<Array<string>>;

export function LoadDirectory(arg1:string):Promise<void>;

export function RefreshPages():Promise<void>;

export function UpdateBlock(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateBlockAtPath(arg1:string,arg2:main.BlockPath,arg3:string):Promise<Record<string, any>>;
